Include new repos in thoth-station and remove old team members
thoth-station/core pull request #380
Opened 2022-02-10 21:22 UTC by harshad16

Include new repos in thoth-station and remove old team members
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### Description

Firstly, Thanks for all the contributions for the member of the thoth-station, who are no longer part of this.

1. Fix the membership: ![team-members](https://user-images.githubusercontent.com/14028058/153498532-610239bf-8d19-48af-9e54-6441962083b9.png)

- Removed a few of the old team members from org, they would still be able to contribute as open-source contributors.
- Removed some team members who are part of Open Services Group, however haven't accepted the thoth-station invite for more than a month. Taking as they would like to stay open source contributor instead of the team member of thoth-station.

 2. Added the repo which were not tracked in here.

2022-02-10 21:22 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **harshad16** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fcore).

<details open>
Needs approval from an approver in each of these files:

- **[community/OWNERS](https://github.com/thoth-station/core/blob/master/community/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2022-02-10 21:22 UTC, sesheta commented
@harshad16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
community-management/prow/peribolos | fb54eb0eb27ce6e87fdbf9a5b28944a8984c1df8 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_core/380/peribolos/1491885307048497152) | true | `/test peribolos`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=core&pr=380). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Aharshad16). Please help us and [open an issue](https://github.com/thoth-station/core/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-10 21:41 UTC, harshad16 commented
/override peribolos

2022-02-11 10:26 UTC, codificat reviewed
/lgtm

Just a question about one of the repos.

Also, what happened to the peribolos check?
/retest

2022-02-11 10:26 UTC, sesheta commented
@harshad16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
community-management/prow/peribolos | fb54eb0eb27ce6e87fdbf9a5b28944a8984c1df8 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_core/380/peribolos/1492082534228430848) | true | `/test peribolos`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=core&pr=380). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Aharshad16). Please help us and [open an issue](https://github.com/thoth-station/core/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-11 10:31 UTC, codificat commented
> Also, what happened to the peribolos check?

Ah, for the record: it's trying to prevent mass murder:

```json
{
  "component": "unset",
  "file": "prow/cmd/peribolos/main.go:209",
  "func": "main.main",
  "level": "fatal",
  "msg": "Configuration failed: failed to configure thoth-station members: cannot delete 4 memberships or 0.182 of thoth-station (exceeds limit of 0.150)",
  "severity": "fatal",
  "time": "2022-02-11T10:26:32Z"
}
```

that should be fine this time.
/override community-management/prow/peribolos

2022-02-11 15:13 UTC, harshad16 commented on community/github-config.yaml
> +        archived: true
sounds good to me.
@goern  or @fridex  ack ?

2022-02-14 09:49 UTC, codificat commented
/unassign
as I can't approve or override this one

2022-02-14 09:51 UTC, fridex commented on community/github-config.yaml
> +        archived: true
+1

2022-02-14 13:29 UTC, goern requested changes

2022-02-14 13:29 UTC, goern commented on community/github-config.yaml
> +        archived: true
+1

2022-02-14 13:29 UTC, goern commented on community/github-config.yaml
> +      rapidsai-build:
is that something we can archive?

2022-02-14 16:53 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2022-02-14 16:53 UTC, sesheta commented
@harshad16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
community-management/prow/peribolos | 841a5d63b2732d16e63e5ae2cc6cc9de9d1a00da | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_core/380/peribolos/1493267175127912448) | true | `/test peribolos`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=core&pr=380). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Aharshad16). Please help us and [open an issue](https://github.com/thoth-station/core/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-14 16:53 UTC, harshad16 commented on community/github-config.yaml
> +        archived: true
Done, will delete as soon this pr is merged.

2022-02-14 16:54 UTC, harshad16 commented on community/github-config.yaml
> +      rapidsai-build:
yes, archived it with this pr

2022-02-14 16:54 UTC, harshad16 commented
Ready for review.

2022-02-17 16:46 UTC, goern commented
/approve

2022-02-17 16:46 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/core/pull/380#issuecomment-1043172734" title="Approved">goern</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fcore).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[community/OWNERS](https://github.com/thoth-station/core/blob/master/community/OWNERS)~~ [goern]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-02-21 08:23 UTC, merged