Adding VannTen (Max Gautier) as project member
thoth-station/core pull request #420
Opened 2022-07-01 14:11 UTC by VannTen

2022-07-01 14:11 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **harshad16** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @harshad16` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fcore).

<details open>
Needs approval from an approver in each of these files:

- **[community/OWNERS](https://github.com/thoth-station/core/blob/master/community/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2022-07-01 14:12 UTC, sesheta commented
Hi @VannTen. Thanks for your PR.

I'm waiting for a [thoth-station](https://github.com/orgs/thoth-station/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/thoth-station/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fcore).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-07-04 14:38 UTC, harshad16 requested changes
lgtm
can you add yourself in the team `devs` as a member
https://github.com/thoth-station/core/blob/a6bd40e5cb89fa4a2475cd896f625a52f12f5c78/community/github-config.yaml#L1013

2022-07-04 16:20 UTC, harshad16 commented
/ok-to-test

2022-07-07 08:40 UTC, codificat commented
/approve

Welcome aboard!

2022-07-07 08:43 UTC, merged